site_name: 3DCoded
site_url: https://3dcoded.xyz
repo_url: https://github.com/3dcoded/
plugins:
  - search
  - autolinks
  - blog
markdown_extensions:
  - pymdownx.critic
  - pymdownx.snippets:
      base_path: docs/snippets
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
theme:
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
      - navigation.indexes
      # - navigation.expand
      - navigation.tabs
      - navigation.instant
      - navigation.instant.prefetch
      - search.suggest
      - search.highlight
      - search.share
      - content.code.copy
      - content.code.annotate
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - 3MS: https://3ms.3dcoded.xyz
  - DynamicMacros:
    - DynamicMacros/index.md
    - DynamicMacros/github.md
    - DynamicMacros/setup.md
    - Tutorial:
      - DynamicMacros/tutorial/index.md
      - DynamicMacros/tutorial/converting.md
      - DynamicMacros/tutorial/usingfeatures.md
      - DynamicMacros/tutorial/experimental.md
    - Features:
      - DynamicMacros/features/index.md
      - DynamicMacros/features/recursion.md
      - DynamicMacros/features/receivingvariables.md
      - DynamicMacros/features/utilities.md
      - DynamicMacros/features/variables.md
      - DynamicMacros/features/python.md
      - DynamicMacros/features/delayed.md
      - DynamicMacros/features/clusters.md
      - DynamicMacros/features/rendering.md
    - DynamicMacros/examples.md
  - KlipperMaintenance:
    - Home: KlipperMaintenance/index.md
    - KlipperMaintenance/github.md
    - KlipperMaintenance/install.md
    - KlipperMaintenance/config.md
    - KlipperMaintenance/gcodes.md
  - Klippy Extras:
    - extras/extras-start.md
    - extras/extras-intro.md
    - extras/extras-ex1.md
    - extras/extras-ex2.md
    - extras/extras-ex3.md